<?php

namespace App\Entity\Repository;

/**
 * Erpn_out_svod_inn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Erpn_out_svod_inn extends \Doctrine\ORM\EntityRepository
{
}
