<?php

namespace App\Entity\Repository;

/**
 * LoadFile
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoadFile extends \Doctrine\ORM\EntityRepository
{
}
