App\Entity\Errorloadreestr:
    type: entity
    table: ErrorLoadReestr
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: Id
            generator:
                strategy: IDENTITY
    fields:
        keyField:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                comment: 'ключевое поле '
            column: key_field
        typereestr:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                comment: 'тип реестра In/Out'
            column: TypeReestr
        error:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
                comment: 'Описание ошибки валидации '
            column: Error
        numbranch:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
                comment: 'Номер филиала '
            column: numBranch
    lifecycleCallbacks: {  }
